/* constants.h (ejo@ufo) 10 Sep 23  Modified: 10 Sep 23  09:22 */

#ifndef CONSTANTS_H
#define CONSTANTS_H


#define USER_MODE      0
#define TIMER_MODE     1
#define INTERRUPT_MODE 2

#define USER_PROGRAM_LOAD         0
#define TIMER_PROGRAM_LOAD     1000
#define INTERRUPT_PROGRAM_LOAD 1500
#define END_OF_MEMORY          2000

#define USTACK_BASE  999
#define SSTACK_BASE 1999

#define CHECK_ADDRESS(ADDR, MODE) (((MODE)==USER_MODE) && ((ADDR) > USTACK_BASE))

#define IS_ADDRESS_IN_RANGE(ADDR, START, STOP) (((ADDR)>=(START)) && ((ADDR)<(STOP)))
#define IS_USER_ADDRESS(ADDR) IS_ADDRESS_IN_RANGE(ADDR, USER_PROGRAM_LOAD, TIMER_PROGRAM_LOAD)
#define IS_TIMER_ADDRESS(ADDR) IS_ADDRESS_IN_RANGE(ADDR, TIMER_PROGRAM_LOAD, INTERRUPT_PROGRAM_LOAD)
#define IS_INTERRUPT_ADDRESS(ADDR) IS_ADDRESS_IN_RANGE(ADDR, INTERRUPT_PROGRAM_LOAD, END_OF_MEMORY)

#define CONSOLE stderr

#endif	/* CONSTANTS_H */
